export const ARTICLES = [
    {
        id:0,
        title: "New Site Launched!",
        author: "Jake Genera",
        date: "2019-09-20T16:49Z",
        subhead: "Special thanks to my web developer, Nic Addelia.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non metus metus. Ut id orci vitae libero posuere sollicitudin. Cras metus nulla, sodales eget lobortis mattis, consectetur sed massa. Donec volutpat risus pulvinar, maximus lectus quis, fermentum enim. Donec ac efficitur velit. Sed sed vulputate diam. Nulla auctor ac ligula at hendrerit. In hac habitasse platea dictumst. Morbi quis molestie tellus, at dapibus neque. Vivamus tempus, quam in mattis varius, ipsum sapien tempor nisl, sed euismod nulla libero a risus. Duis nisi est, aliquet sit amet est sit amet, euismod vestibulum enim. Donec vitae tortor condimentum ex convallis varius. Integer at accumsan mi, a placerat ligula. Sed tincidunt non lorem et elementum. In varius aliquet massa, non pretium ipsum ultrices eget. Donec consectetur orci eget urna blandit, quis tincidunt lorem ullamcorper. Nam efficitur mauris sit amet laoreet dignissim. Pellentesque ornare elit eu augue ultricies, auctor tincidunt sem lobortis. Donec faucibus justo quis tortor vestibulum, quis mollis massa blandit. Suspendisse laoreet nibh eget massa sagittis rhoncus eget et ligula. Vestibulum cursus nunc vel semper varius. Morbi hendrerit neque nec ligula tempor, vitae pellentesque libero congue. Nullam at tellus consectetur, commodo felis quis, interdum lorem. Suspendisse id neque metus. Curabitur posuere purus ut elementum mollis. Etiam quis felis ut lacus lacinia molestie eget in sem. Quisque tempor commodo sem, et placerat tortor tempus sit amet. Donec volutpat at nunc sed varius. Mauris faucibus diam vitae urna ultricies interdum. Nulla venenatis turpis malesuada erat ullamcorper, id rutrum nunc porta.",
        featured: false
    },
    {
        id:1,
        title: "My Musical Philosophy",
        author: "Jake Genera",
        date: "2019-10-18T20:05Z",
        subhead: "Music means the world to me. Here's why.",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non metus metus. Ut id orci vitae libero posuere sollicitudin. Cras metus nulla, sodales eget lobortis mattis, consectetur sed massa. Donec volutpat risus pulvinar, maximus lectus quis, fermentum enim. Donec ac efficitur velit. Sed sed vulputate diam. Nulla auctor ac ligula at hendrerit. In hac habitasse platea dictumst. Morbi quis molestie tellus, at dapibus neque. Vivamus tempus, quam in mattis varius, ipsum sapien tempor nisl, sed euismod nulla libero a risus. Duis nisi est, aliquet sit amet est sit amet, euismod vestibulum enim. Donec vitae tortor condimentum ex convallis varius. Integer at accumsan mi, a placerat ligula. Sed tincidunt non lorem et elementum. In varius aliquet massa, non pretium ipsum ultrices eget. Donec consectetur orci eget urna blandit, quis tincidunt lorem ullamcorper. Nam efficitur mauris sit amet laoreet dignissim. Pellentesque ornare elit eu augue ultricies, auctor tincidunt sem lobortis. Donec faucibus justo quis tortor vestibulum, quis mollis massa blandit. Suspendisse laoreet nibh eget massa sagittis rhoncus eget et ligula. Vestibulum cursus nunc vel semper varius. Morbi hendrerit neque nec ligula tempor, vitae pellentesque libero congue. Nullam at tellus consectetur, commodo felis quis, interdum lorem. Suspendisse id neque metus. Curabitur posuere purus ut elementum mollis. Etiam quis felis ut lacus lacinia molestie eget in sem. Quisque tempor commodo sem, et placerat tortor tempus sit amet. Donec volutpat at nunc sed varius. Mauris faucibus diam vitae urna ultricies interdum. Nulla venenatis turpis malesuada erat ullamcorper, id rutrum nunc porta.",
        featured: true
    },
    {
        id:2,
        title: "New Shows Added!",
        author: "Jake Genera",
        date: "2020-02-29T12:00Z",
        subhead: "Get these on your calendar today!",
        text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce non metus metus. Ut id orci vitae libero posuere sollicitudin. Cras metus nulla, sodales eget lobortis mattis, consectetur sed massa. Donec volutpat risus pulvinar, maximus lectus quis, fermentum enim. Donec ac efficitur velit. Sed sed vulputate diam. Nulla auctor ac ligula at hendrerit. In hac habitasse platea dictumst. Morbi quis molestie tellus, at dapibus neque. Vivamus tempus, quam in mattis varius, ipsum sapien tempor nisl, sed euismod nulla libero a risus. Duis nisi est, aliquet sit amet est sit amet, euismod vestibulum enim. Donec vitae tortor condimentum ex convallis varius. Integer at accumsan mi, a placerat ligula. Sed tincidunt non lorem et elementum. In varius aliquet massa, non pretium ipsum ultrices eget. Donec consectetur orci eget urna blandit, quis tincidunt lorem ullamcorper. Nam efficitur mauris sit amet laoreet dignissim. Pellentesque ornare elit eu augue ultricies, auctor tincidunt sem lobortis. Donec faucibus justo quis tortor vestibulum, quis mollis massa blandit. Suspendisse laoreet nibh eget massa sagittis rhoncus eget et ligula. Vestibulum cursus nunc vel semper varius. Morbi hendrerit neque nec ligula tempor, vitae pellentesque libero congue. Nullam at tellus consectetur, commodo felis quis, interdum lorem. Suspendisse id neque metus. Curabitur posuere purus ut elementum mollis. Etiam quis felis ut lacus lacinia molestie eget in sem. Quisque tempor commodo sem, et placerat tortor tempus sit amet. Donec volutpat at nunc sed varius. Mauris faucibus diam vitae urna ultricies interdum. Nulla venenatis turpis malesuada erat ullamcorper, id rutrum nunc porta.",
        featured: false
    }
]